# Site settings
title: Personal Portfolio | Giannopoulos Panagiotis
description: Data Science Portfolio
# baseurl: "/particle" # the subpath of your site, e.g. /blog
url: "https://panagiotisgia.github.io" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Giannopoulos Panagiotis
user_description: Bicycle rights irony actually neutra typewriter lyft. Man bun taxidermy put a bird on it, umami yr ramps pop-up ugh bushwick chia lo-fi. Occupy bitters pour-over snackwave you probably haven't heard of them small batch. Cornhole mustache man bun letterpress echo park VHS.
user_title: Data Enthusiast
email: panagiotisgia@hotmail.com
twitter_username: Panagiotisgia2
github_username:  panagiotisgia
gplus_username:  ""
linkedin_username: panagiotisgia
facebook_username: panagiotis.giannopoulos.397

# Google-analytics
google-analytics:
  id: ""

exclude: ['package.json', 'src' , 'node_modules']



#