# Site settings
title: Personal Portfolio | Giannopoulos Panagiotis
description: Data Science Portfolio
# baseurl: "/particle" # the subpath of your site, e.g. /blog
url: "https://panagiotisgia.github.io" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Giannopoulos Panagiotis
user_description: As a devoted Data Science enthusiast with a MSc degree, I love helping numbers tell their stories and finding useful information within them. I stay updated on the latest trends in Machine Learning and AI, and I use Big Data tools and Blockchain analytics to connect data with real-world value.                                                                 By constantly improving my skills, I aim to turn complex data into practical insights that make a difference in businesses and drive growth. Join me as I explore the exciting world of data, where numbers create powerful stories that inspire change.
user_title: Data Scientist
email: panagiotisgia@hotmail.com
twitter_username: Panagiotisgia2
github_username:  panagiotisgia
gplus_username:  ""
linkedin_username: panagiotisgia
facebook_username: panagiotis.giannopoulos.397

# Google-analytics
google_analytics: G-575EF3S0GF
  

exclude: ['package.json', 'src' , 'node_modules']



#
