# Site settings
title: Personal Portfolio | Giannopoulos Panagiotis
description: Data Science Portfolio
# baseurl: "/particle" # the subpath of your site, e.g. /blog
url: "https://panagiotisgia.github.io" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Giannopoulos Panagiotis
user_description: As a devoted Data Alchemist with an MSc degree in Data Science, I strive to find an edge with passion by transforming data into actionable insights. I stay updated on the latest trends in AI and Machine Learning, using Big Data tools to optimize my work efficiently. After all, it is our duty to help numbers tell their stories and find useful information within them.
user_title: Data Alchemist
email: panagiotisgia@hotmail.com
twitter_username: Panagiotisgia2
github_username:  panagiotisgia
gplus_username:  ""
linkedin_username: panagiotisgia
facebook_username: panagiotis.giannopoulos.397

# Google-analytics
google_analytics: G-NXTW3318BK
  

exclude: ['package.json', 'src' , 'node_modules']



#
